# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false
    end

    config.vm.define :bookworm do |bookworm_config|
        bookworm_config.vm.box = "ubuntu/trusty64"
        bookworm_config.vm.hostname = "book-worm"
        bookworm_config.vm.network :private_network, ip: "192.168.0.10"
        bookworm_config.vm.network :forwarded_port, guest: 80, host: 8080 # forwards localhost:8080 to port 80 on the vm

        bookworm_config.vm.provider :virtualbox do |bookworm_vb|
            bookworm_vb.name = "book-worm"
            bookworm_vb.customize ["modifyvm", :id, "--memory", "1024"]
            bookworm_vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
            bookworm_vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            bookworm_vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        end

        bookworm_config.vm.provision :shell, :path => "scripts/setup.sh"
    end
end
